services:
  test_db:
    image: postgres:15
    container_name: test_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskmanager_test
    ports:
      - "5433:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d taskmanager_test"]
      interval: 1s
      timeout: 2s
      retries: 30
      

volumes:
  test_db_data: